# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precioUnitario', models.CharField(max_length=60)),
                ('stockActual', models.CharField(max_length=60)),
                ('stockMinimo', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Almacen',
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseImponible', models.CharField(max_length=60)),
                ('fechaDocumento', models.CharField(max_length=60)),
                ('igv', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=60)),
                ('serie', models.CharField(max_length=60)),
                ('tipoDocumento', models.CharField(max_length=60)),
                ('total', models.CharField(max_length=60)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Almacen')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=60)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Compra')),
            ],
            options={
                'verbose_name': 'DetalleCompra',
                'verbose_name_plural': 'DetalleCompras',
            },
        ),
        migrations.CreateModel(
            name='DetalleOs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=60)),
                ('puSalida', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'DetalleOs',
                'verbose_name_plural': 'DetalleOss',
            },
        ),
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'Farmacia',
                'verbose_name_plural': 'Farmacias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='OrdenSalida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseImponible', models.CharField(max_length=60)),
                ('igv', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=60)),
                ('serie', models.CharField(max_length=60)),
                ('tipoDocumento', models.CharField(max_length=60)),
                ('total', models.CharField(max_length=60)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Almacen')),
            ],
            options={
                'verbose_name': 'OrdenSalida',
                'verbose_name_plural': 'OrdenSalidas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=60)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Almacen')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.Categoria')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repositorio.Marca')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=60)),
                ('razonSocial', models.CharField(max_length=60)),
                ('representanteLegal', models.CharField(max_length=60)),
                ('ruc', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'UnidadMedida',
                'verbose_name_plural': 'UnidadMedidas',
            },
        ),
        migrations.AddField(
            model_name='detalleos',
            name='ordenSalida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.OrdenSalida'),
        ),
        migrations.AddField(
            model_name='detalleos',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Producto'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Proveedor'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Farmacia'),
        ),
    ]
