# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-04 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0004_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='farmacia',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='detalleos',
            name='ordenSalida',
        ),
        migrations.RemoveField(
            model_name='detalleos',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='ordensalida',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='almacen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='UnidadMedida',
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
        migrations.DeleteModel(
            name='DetalleOs',
        ),
        migrations.DeleteModel(
            name='Farmacia',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='OrdenSalida',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
