# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0009_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
