# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0011_auto_20171104_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
