# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0015_detalleunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleunidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
