# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0016_auto_20171105_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleunidad',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='DetalleUnidad',
        ),
    ]
