# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0024_tiempoalquiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=60, null=True)),
                ('distancia_km', models.CharField(max_length=20)),
                ('lugar_origen', models.CharField(max_length=60)),
                ('lugar_destino', models.CharField(max_length=60)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
            },
        ),
    ]
