# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0027_detalletiempoalquiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTarifario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('tarifario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Tarifario')),
            ],
            options={
                'verbose_name': 'DetalleTarifario',
                'verbose_name_plural': 'DetalleTarifarios',
            },
        ),
    ]
