# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0028_detalletarifario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Cliente')),
                ('detalleTarifario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.DetalleTarifario')),
                ('detalleTiempoAlquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.DetalleTiempoAlquiler')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Ruta')),
            ],
            options={
                'verbose_name': 'Alquiler',
                'verbose_name_plural': 'Alquileres',
            },
        ),
    ]
