# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0029_alquiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='cargopersonal',
            name='personal',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
