# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0030_auto_20171113_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=40)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Alquiler')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Persona')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
            },
        ),
    ]
