# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0031_personal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CargoPersonal',
        ),
    ]
