# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-13 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0032_delete_cargopersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoPersonal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True)),
                ('funcion', models.CharField(max_length=40)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizada', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.Personal')),
            ],
            options={
                'verbose_name': 'CargoPersonal',
                'verbose_name_plural': 'CargoPersonales',
            },
        ),
    ]
