# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-14 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0033_cargopersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recepcionunidad',
            name='persona',
        ),
        migrations.DeleteModel(
            name='RecepcionUnidad',
        ),
    ]
